name: taba3ni
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # services
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  location: ^4.4.0
  crossplat_objectid: ^3.0.0
  google_sign_in: ^5.3.2
  connection_notifier: ^0.0.1
  custom_marker: ^1.0.0

  # style & UI
  google_fonts: ^3.0.1
  flutter_native_splash: any
  flutter_launcher_icons: "^0.9.2"
  flutter_svg: any
  animated_theme_switcher: ^2.0.6
  carousel_slider: ^4.1.1

  # firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any
  firebase_core_platform_interface: 4.4.0

  #location
  geolocator: ^9.0.0
  google_maps_flutter: ^2.1.6
  background_locator_2: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^1.0.4


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

