// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2BrEGtSD2OIUHquHTapQRKEhGlZdxhhs',
    appId: '1:138671267539:web:73131876f0ceaf0c44be26',
    messagingSenderId: '138671267539',
    projectId: 'taba3ni-19b1b',
    authDomain: 'taba3ni-19b1b.firebaseapp.com',
    storageBucket: 'taba3ni-19b1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxj3l3aN5upLLnQiYnRgj1MyYO3ow-Q50',
    appId: '1:138671267539:android:79e6a0938215f24644be26',
    messagingSenderId: '138671267539',
    projectId: 'taba3ni-19b1b',
    storageBucket: 'taba3ni-19b1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCIe0bxEzoZ2qlqWQ85n3sX1vIKtSJX7I',
    appId: '1:138671267539:ios:97db0c91923651ce44be26',
    messagingSenderId: '138671267539',
    projectId: 'taba3ni-19b1b',
    storageBucket: 'taba3ni-19b1b.appspot.com',
    iosClientId: '138671267539-a3gdsub8gk5u6sji9j8fal1shms03le3.apps.googleusercontent.com',
    iosBundleId: 'com.example.taba3ni',
  );
}
